// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzn5XLbsr4Kxw8fmBFTHgACwShJFksekY',
    appId: '1:938215011602:android:664266880000ff3bbbefcb',
    messagingSenderId: '938215011602',
    projectId: 'fir-project-d4e6b',
    storageBucket: 'fir-project-d4e6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7CH_BP-69C9ab7Pvygt88Ycd_pAQfiE4',
    appId: '1:938215011602:ios:7812f1213636a4a4bbefcb',
    messagingSenderId: '938215011602',
    projectId: 'fir-project-d4e6b',
    storageBucket: 'fir-project-d4e6b.appspot.com',
    androidClientId: '938215011602-66ik6kvnpg5a1p7h13k0srmm5hbp6b94.apps.googleusercontent.com',
    iosClientId: '938215011602-2ue4qjbabntgtaak4prqfk57k15ua8jv.apps.googleusercontent.com',
    iosBundleId: 'uz.mobilepro.coder.planetPhoneDashboard',
  );
}
